# ./docker-compose.yml
version: '3'

networks:
  meme-generator-net:
    external: true
    name: "meme-generator-net"

services:
  app:
    image: adhocore/lemp:8.1
    # For different app you can use different names. (eg: )
    container_name: memegenerator
    volumes:
      # app source code
      - ./html:/var/www/html
      # db data persistence
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepwd
      MYSQL_DATABASE: appdb
      MYSQL_USER: dbusr
      MYSQL_PASSWORD: securepwd
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix
    networks:
      - "meme-generator-net"
    restart: always

    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_memegenerator
    restart: always
    environment:
      - PMA_HOST=app
      - PMA_PORT=3306
    networks:
      - "meme-generator-net"

volumes:
  db_data: {}